const mongoose = require("mongoose");
const { Schema } = mongoose;

const RepositorySchema = new Schema({
  // This will be the unique ID generated by your 'init' command
  s3RepoId: {
    type: String,
    required: true,
    unique: true,
  },
  name: {
    type: String,
    required: true,
  },
  description: {
    type: String,
  },
  owner: {
    type: Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  // We can add more features like this later
  isPublic: {
    type: Boolean,
    default: true,
  },
}, { timestamps: true });

const Repository = mongoose.model("Repository", RepositorySchema);
module.exports = Repository;
